spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quant-craft
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: postgresql

logging:
  level:
    org.hibernate.SQL: debug
